version: "3.9"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 82:80/tcp
    volumes:
      - /home/pi/luna_data/adguardhome/work:/opt/adguardhome/work
      - /home/pi/luna_data/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
